{% set version = "22.05.6" %}

package:
  name: slurm
  version: {{ version }}

source:
  url: https://download.schedmd.com/slurm/slurm-{{ version }}.tar.bz2
  sha256: e3cbbf0e3330f281a1472aba1298136e27ddbc4d10f471c211dbe9f21a56d801

build:
  skip: true  # [not linux]
  number: 0

requirements:
  build:
    - make
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - munge
    - mysql-devel
    - bzip2
    - libzlib
    - zstd
    - openssl
    - libcurl
    - krb5
    - keyutils
    - libedit
  run:
    - munge

test:
  commands:
    - slurmd -h
    - slurmctld -h
    - test -f $PREFIX/bin/sacct
    - test -f $PREFIX/bin/salloc
    - test -f $PREFIX/bin/sprio
    - test -f $PREFIX/bin/srun
    - test -f $PREFIX/bin/sshare
    - test -f $PREFIX/bin/sstat
    - test -f $PREFIX/bin/strigger

about:
  home: https://slurm.schedmd.com/
  summary: cluster management and job scheduling system for Linux clusters
  license: GPL-2.0-only
  license_family: GPL2
  license_file: COPYING

extra:
  recipe-maintainers:
    - msarahan
